### ISSUE TITLE
Application Error event in the explainer

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-lifecycle#1]
In the lifecycle [explainer](https://github.com/w3c/miniapp/blob/gh-pages/specs/lifecycle/docs/explainer.md), the "Lifecycle States defined by existing W3C specs" is "N/A".

I wonder if we can use the [error](https://w3c.github.io/uievents/#event-type-error) event on `Element`/`Window`?

**Comment by QingAn** [comment]
> In the lifecycle [explainer](https://github.com/w3c/miniapp/blob/gh-pages/specs/lifecycle/docs/explainer.md), the "Lifecycle States defined by existing W3C specs" is "N/A".
> 
> I wonder if we can use the [error](https://w3c.github.io/uievents/#event-type-error) event on `Element`/`Window`?

I edited the explainer and created a pull request. But I am wondering that since MiniApp's runtime is different with web runtime, is it necessary to use the error event on Element/Window?

**Comment by xfq** [comment]
I don't quite understand what "use the error event" means here. According to my understanding, we are looking for a mapping to existing Web specifications, rather than directly using this event.

**Comment by xfq** [comment]
Link to PR: https://github.com/w3c/miniapp-lifecycle/pull/6

**Comment by QingAn** [comment]
> I don't quite understand what "use the error event" means here. According to my understanding, we are looking for a mapping to existing Web specifications, rather than directly using this event.

Then I made a mistaken assumption. I think we can agree that the goal is to make the mapping happen. 
So, back to the explainer, can we agree on the PR: #6?
