### ISSUE TITLE
About the referrerInfo attribute

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-lifecycle#24]
https://w3c.github.io/miniapp-lifecycle/#referrerinfo-attribute

> The `referrerInfo` attribute contains the source info for the MiniApp, including MiniApp ID, and optional extra data.

This attribute is a string, but it is not clear what the specific structure of the string is and what the "optional extra data" contains.

**Comment by QingAn** [comment]
It can include natural language text. So I18N should be applied here.

**Comment by QingAn** [comment]
@xfq Can this issue be closed? Since #29 has addressed this issue.

**Comment by xfq** [comment]
I'll confirm at the next i18n WG teleconference.

**Comment by xfq** [comment]
The i18n WG is satisfied with the resolution. Thank you!
