### ISSUE TITLE
Language and direction metadata for errorDescription

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-lifecycle#25]
https://w3c.github.io/miniapp-lifecycle/#lifecycleerror-interface

> The `errorDescription` attribute is a developer-friendly textual description of the error global application lifecycle states.

It is a natural language, human-readable string, but there are no language and direction metadata associated with it.

For more info, see:

* https://www.w3.org/International/articles/lang-bidi-use-cases/
* https://w3c.github.io/bp-i18n-specdev/#errors
* https://github.com/w3c/i18n-discuss/blob/gh-pages/explainers/string-meta-explainer.md
* https://w3c.github.io/string-meta/
* https://github.com/w3ctag/design-reviews/issues/716

**Comment by QingAn** [comment]
The PR #29 is to address this issue.

**Comment by QingAn** [comment]
@xfq Can this issue be closed?

**Comment by xfq** [comment]
I'll confirm at the next i18n WG teleconference.

**Comment by xfq** [comment]
The i18n WG is satisfied with the resolution. Thank you!
