### ISSUE TITLE
MiniApp URI in the explainer

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-lifecycle#28]
https://github.com/w3c/miniapp-lifecycle/blob/main/docs/explainer.md#sample-code

> Assume MiniApp URI is: `miniapp://foo;version=1.0.1-trial@example.com:8080/pages/index?k=v#bar`

It should be updated to use the new format in [MiniApp Addressing](https://w3c.github.io/miniapp-addressing/).

**Comment by QingAn** [comment]
Updated. I think this issue is ok to be closed. @xfq

**Comment by xfq** [comment]
Thank you!
