### ISSUE TITLE
Define "first render" in the Lifecycle spec

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-lifecycle#3]
https://w3c.github.io/miniapp/specs/lifecycle/

The spec mentions the term "first render" a few times, but without a clear definition of it, it will be difficult to for a user agent implement and test it.

**Comment by QingAn** [comment]
Add a Note in #9 to define the first render

**Comment by xfq** [comment]
Since we have a definition now, I will close this issue. If necessary, we can file new issues and further improve the text in the future.
