### ISSUE TITLE
use of of callbacks instead of events

### ISSUE THREAD

**Issue by pes10k** [w3c/miniapp-lifecycle#30]
This issue is being filed as part of of PING's [horizontal review](https://github.com/w3cping/privacy-request/issues/93)

The spec uses a callback for each event, instead of the general event registration model used on the Web.  This has the downsides of making it more difficult to register multiple behaviors for a single event, and populating the global namespace.  Has the group considered using the more common (on the web at least) event registration / addEventListener model instead?  If so and the group decided against it, it might be valuable to include a non-normative note in the spec explaining why callbacks were selected instead

This is not a blocking privacy issue, but im mentioning it since it came up during the review

**Comment by QingAn** [comment]
@pes10k #33 has been merged to change from callbacks to events. Please take a look. I think it can resolve the issue.

**Comment by pes10k** [comment]
this looks like an improvement, but I think you also need to define one more more Event types that get propagated when these events are triggered

**Comment by QingAn** [comment]
> but I think you also need to define one more more Event types that get propagated when these events are triggered

@pes10k Could you explain more about this? Or is there any example? Thanks

**Comment by pes10k** [comment]
Sure, a very common pattern on the Web is for new proposals to extend the platform's default [`Event`](https://developer.mozilla.org/en-US/docs/Web/API/Event) interface, to more specific event types. For example, [`MessageEvent`](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent), though its a very common pattern.  

Then, JS code can register to handle those events, sometimes using the legacy DOM0 approach (`onclick`, `onerror` etc), but more commonly using the [`addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).

Hope this helps!

**Comment by QingAn** [comment]
After discussing with MiniApp WG, the WG concludes to keep the current WebIDL design (not define the Event types for now)

So, if no more comment, this issue will be closed.
