### ISSUE TITLE
Under definition of some properties and elements

### ISSUE THREAD

**Issue by pes10k** [w3c/miniapp-lifecycle#31]
This issue is being filed as part of of PING's [horizontal review](https://github.com/w3cping/privacy-request/issues/93)

In some places the spec is missing context or descriptive text explaining what purpose different features and values have.  To give just one example, section 2.5.1. says, effectively that the "inputQuery property contains the input query for the mini app", without any explanation of what an input query is.  This makes implementation difficult (how does the implementor know what should go here) and reduces the value of the spec for application authors).  The input query example is not the only case where the spec seems under defined.

I suggest adding more explanation in these cases and / or linking to definitions 

This is not a blocking privacy issue, but im mentioning it since it came up during the review

**Comment by QingAn** [comment]
@pes10k The #36 is purposed to resolve this issue. Please take a look.

Note: some optional properties have been removed. So I believe only the pageInputQuery property needs further definition.

**Comment by pes10k** [comment]
I think this is an improvement, but this text seems circular, and could probably be further clarified, for my 2c

> The <dfn>pageInputObject</dfn> contains pageInputQuery for loading the MiniApp page

**Comment by QingAn** [comment]
> I think this is an improvement, but this text seems circular, and could probably be further clarified, for my 2c
> 
> > The pageInputObject contains pageInputQuery for loading the MiniApp page

@pes10k The detailed description is in the section of 3.5.1 pageInputQuery. Because I don't want to repeat the description :)

**Comment by pes10k** [comment]
I leave it to you all to decide whats best (i just meant this issue as a suggestion). But, for my 2c, saying the `pageInputObject` contains the `pageInputQuery` doesn't help me understand (to my read) what either of those things are.  If they're defined elsewhere, maybe either i) inlining the definition, or ii) linking to it, would be clarifying.

That said, again, this is just a suggestion answer, not one that needs resolution PING side

**Comment by QingAn** [comment]
The #36 has been merged to solve this issue. 

(A linking a added to provide clearer clarification)
