### ISSUE TITLE
Accessibility Considerations text is confusing or incorrect

### ISSUE THREAD

**Issue by pes10k** [w3c/miniapp-lifecycle#32]
This issue is being filed as part of of PING's [horizontal review](https://github.com/w3cping/privacy-request/issues/93)

The current accessibility considerations section says (in total) 

> As MiniApp Lifecycle is not user aware and does not involve user interaction, accessibility consideration is not needed in this specification.

This seems incorrect or misleading since many of these events will happen because of user interaction, no? (the app being launched, a page being shown, closed and / or switched with another, etc)

This is not a blocking privacy issue, but im mentioning it since it came up during the review

**Comment by QingAn** [comment]
> This seems incorrect or misleading since many of these events will happen because of user interaction, no? (the app being launched, a page being shown, closed and / or switched with another, etc)

@pes10k In this case, yes, MiniApp Lifecycle change is triggered by user interaction. MiniApp Lifecycle spec defines GlobalState and PageState to indicate whether the MiniApp is shown or hidden, which can be used to accommodate assistive technologies. 

Does it address this issue by adding some text description like the above in the Accessibility Considerations section?

**Comment by pes10k** [comment]
Yep, just clarifying that the proposal does involve (sometimes) responding to user interactions would be sufficient here.  Thanks!

**Comment by QingAn** [comment]
resolved
