### ISSUE TITLE
The <body> is marked as informative 

### ISSUE THREAD

**Issue by espinr** [w3c/miniapp-lifecycle#38]
I see that the `<body>` of the specification document is marked as `informative`. 

This raises some inconsistency errors when we use reSpec. 

````html
<body class="h-entry informative"
````

Thanks!

**Comment by QingAn** [comment]
@espinr Do you mean in this spec?: https://github.com/w3c/miniapp-lifecycle/blob/main/index.html

But I didn't find `<body class="h-entry informative"` in the above document.

**Comment by espinr** [comment]
Ouch... You are right @QingAn. There are only four sections marked as informative. That class must be included by the ReSpec scripts when it's published to `w3.org/TR/`.

I opened this issue because I got the following reSpec warning when [I referenced](https://github.com/w3c/miniapp-packaging/pull/65/files) to `[=Document/launched=]` from the packaging spec: 

>  Normative reference to "launched" found but term is defined "informatively" in "miniapp-lifecycle".

This is why I looked into the code of [the LifeCycle spec](https://www.w3.org/TR/miniapp-lifecycle/) and I found that class in the `<body>`.

I'm sorry for the confusion...  Closing the issue in the meantime.
