### ISSUE TITLE
Definition of RenderView and Worker

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-lifecycle#5]
https://w3c.github.io/miniapp/specs/lifecycle/#miniapp-page-lifecycle-states

It is not clear to me what RenderView means here. It would be useful to add a definition here.

Is Worker a web worker or something else?

**Comment by QingAn** [comment]
In the white paper (https://www.w3.org/TR/2019/WD-mini-app-white-paper-20190912/#separate-the-view-layer-from-the-logic-layer), the terms are View layer and Logic layer.

So, in the lifecycle spec (https://w3c.github.io/miniapp-lifecycle/#background), the same terms are reused as follows: 

As described in MiniApp Standardization White Paper, in a miniapp, the View layer is separated from the Logic layer. The View layer is responsible for rendering MiniApp pages, including Web rendering and native rendering, which can be considered as hybrid rendering. The Logic layer is implemented with JavaScript Worker. The Logic layer is responsible for MiniApp’s event processing, API calling and lifecycle management.

Is it good enough?

**Comment by xfq** [comment]
Looks good to me.
