### ISSUE TITLE
Update mechanism of MiniApps

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-lifecycle#8]
Do we need to write about how a MiniApp is updated? If so, should we write it here or create a new spec?

**Comment by QingAn** [comment]
There are two cases about MiniApp update, which case do you refer to?

1. Version update of the MiniApp, which means to re-download the MiniApp package
2. Update MiniApp page dynamically, which means to fetch real-time content from backend server and to update the MiniApp page in real-time.

**Comment by xfq** [comment]
I mean the first case.

**Comment by QingAn** [comment]
> I mean the first case.

It think this would be orthogonal to lifecycle. I suggest we can discuss it in next CG meeting.

**Comment by xfq** [comment]
Discussions in the CG meeting: https://www.w3.org/2021/06/17-miniapp-minutes.html#t02

**Comment by espinr** [comment]
Feel free to continue the discussion in w3c/miniapp-packaging#28

**Comment by xfq** [comment]
Closing this issue. If we want to update the lifecycle spec, we can open a new issue.

**Comment by awentzel** [comment]
In terms of versioning I think it would be useful to document and would suggest any patterns or algorithms of the version update process follow the latest [Semver](https://semver.org/) spec which is widely adopted across the industry.

**Comment by xfq** [comment]
@awentzel This is currently mentioned in https://w3c.github.io/miniapp-manifest/#sec-version-resources
